### ISSUE TITLE
Error during installation following README.md steps - Missing DJANGO_SECRET_KEY

### ISSUE THREAD

**Issue by henfrydls** [matorral-project/matorral#129]
### Operating System

Windows 11 Pro 23H2

### Python Version

3.12

### Description

Hi,

I encountered an issue while following the installation steps in the README.md. I attempted the installation using both Docker and Hatch, but I received the following error each time:

`Traceback (most recent call last):
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\environ\environ.py", line 388, in get_value
    value = self.ENVIRON[var_name]
            ~~~~~~~~~~~~^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'DJANGO_SECRET_KEY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "path_to_project\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\core\management\base.py", line 104, in wrapper
    saved_locale = translation.get_language()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\utils\translation\__init__.py", line 211, in get_language
    return _trans.get_language()
           ^^^^^^^^^^^^^^^^^^^
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\utils\translation\__init__.py", line 66, in __getattr__
    if settings.USE_I18N:
       ^^^^^^^^^^^^^^^^^
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\conf\__init__.py", line 89, in __getattr__
    self._setup(name)
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\conf\__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\django\conf\__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_python\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames removed
  File "path_to_project\config\settings.py", line 30, in <module>
    SECRET_KEY = env("DJANGO_SECRET_KEY")
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\environ\environ.py", line 199, in __call__
    return self.get_value(
           ^^^^^^^^^^^^^^^
  File "path_to_hatch\env\virtual\matorral\oa8CtWIB\local\Lib\site-packages\environ\environ.py", line 392, in get_value
    raise ImproperlyConfigured(error_msg) from exc
django.core.exceptions.ImproperlyConfigured: Set the DJANGO_SECRET_KEY environment variable
`

**Comment by matagus** [comment]
Hey @henfrydls thanks for reporting this issue. Our [README](https://github.com/matorral-project/matorral/blob/main/README.md#run-using-docker) was missing the step where you need to create the `config/.env` file before starting docker compose or running `hatch run local:server`. The README is updated now.

Let us know how it works for you please.

**Comment by matagus** [comment]
closing this due to no response

@henfrydls feel free to reopen it if you still experience this issue :)
